/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package equivalenciaprogramas;

/**
 *
 * @author Fabricio
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAPrograma2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAPrograma1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtnFazTudo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTAPrograma2.setColumns(20);
        jTAPrograma2.setRows(5);
        jScrollPane1.setViewportView(jTAPrograma2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 337, 370));

        jTAPrograma1.setColumns(20);
        jTAPrograma1.setRows(5);
        jTAPrograma1.setText("SE T1 ENTAO VA_PARA 2 SENAO VA_PARA 3\nFACA F VA_PARA 6\nSE T2 ENTAO VA_PARA J SENAO VA_PARA 4");
        jScrollPane2.setViewportView(jTAPrograma1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 29, 337, 370));

        jLabel1.setText("Programa 1:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, -1, -1));

        jLabel2.setText("Programa 2:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jBtnFazTudo.setText("Faz tudo");
        jBtnFazTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFazTudoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnFazTudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnFazTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFazTudoActionPerformed
        int numLinhas = jTAPrograma1.getLineCount();
        String linhas[] = jTAPrograma1.getText().split("\\n");
        String colunas[];
        
        int maiorNumColunas = -1;
        for (int i = 0; i < linhas.length; i++) {            
            colunas = linhas[i].split(" ");            
            
            if (colunas.length > maiorNumColunas){
                maiorNumColunas = colunas.length;                        
            }
        }
        
        String matrizPrograma1[][] = new String[numLinhas][maiorNumColunas];  
                     
        for (int i = 0; i < linhas.length; i++) {            
            colunas = linhas[i].split(" ");
   
            for (int c = 0; c < colunas.length; c++) {                
                matrizPrograma1[i][c] = colunas[c];                
            }
        }
        
        System.out.println("");
        
        for (int i = 0; i < numLinhas; i++) {
            for (int j = 0; j < maiorNumColunas; j++) {
                if (matrizPrograma1[i][j] != null){                    
                    System.out.println("matriz["+i+"]["+j+"] = "+matrizPrograma1[i][j]);                
                    System.out.println("");
                }
            }            
        }  
        
        /*CRIAR ESTRUTURA PARA CRIAR O PASSO 1*/
    }//GEN-LAST:event_jBtnFazTudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFazTudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAPrograma1;
    private javax.swing.JTextArea jTAPrograma2;
    // End of variables declaration//GEN-END:variables
}
